FROM ubuntu:18.04

WORKDIR /usr/src/install

# Environment variables
ENV PYTHONPATH=\$PYTHONPATH:/usr/local/share/sancus-compiler/python/lib/

# Parameters for Sancus installation
ARG SANCUS_SECURITY=128
ARG SANCUS_KEY=deadbeefcafebabec0defeeddefec8ed

COPY scripts/ .
RUN ./install_sancus.sh $SANCUS_SECURITY $SANCUS_KEY

RUN apt-get update && apt-get install -y git \
    && git clone https://github.com/gianlu33/reactive-uart2ip.git \
    && pip install reactive-uart2ip/

ARG DUMMY=whatever

RUN git clone https://github.com/gianlu33/reactive-net.git \
    && git clone --branch sgx-extension https://github.com/gianlu33/reactive-tools.git \
    && pip install reactive-net/ \
    && pip install reactive-tools/ \
    && rm -rf /usr/src/install

WORKDIR /usr/src/app
