FROM ubuntu:16.04

WORKDIR /usr/src/install

RUN useradd -ms /bin/bash reactive

## Python ##
COPY scripts/install_python.sh .
RUN ./install_python.sh

## Rust ##
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

COPY scripts/install_rust.sh .
RUN ./install_rust.sh

ARG DUMMY1=0

RUN apt-get update && apt-get install -y --no-install-recommends git make \
    && git clone https://github.com/gianlu33/rust-sgx-apps.git \
    && cd rust-sgx-apps && make install_native

ARG DUMMY2=0

RUN git clone https://github.com/gianlu33/reactive-net.git \
    && git clone https://github.com/gianlu33/rust-sgx-gen.git \
    && git clone https://github.com/gianlu33/reactive-tools.git \
    && pip install reactive-net/ rust-sgx-gen/ reactive-tools/ \
    && rm -rf /usr/src/install

WORKDIR /usr/src/app
