FROM ubuntu:18.04

WORKDIR /usr/src/install

# Environment variables
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

COPY scripts/ .
RUN ./install_sgx.sh

ARG DUMMY1=0

RUN apt-get update && apt-get install -y git make \
    && git clone https://github.com/gianlu33/rust-sgx-apps.git \
    && cd rust-sgx-apps && make install

ARG DUMMY2=0

RUN git clone https://github.com/gianlu33/reactive-net.git \
    && git clone https://github.com/gianlu33/rust-sgx-gen.git \
    && git clone --branch sgx-extension https://github.com/gianlu33/reactive-tools.git \
    && pip install reactive-net/ \
    && pip install rust-sgx-gen/ \
    && pip install reactive-tools/ \
    && rm -rf /usr/src/install

WORKDIR /usr/src/app
